export const data = [
  {
    name: 'Books',
    shortDescription: 'Presentation of a book catalog',
    description: '',
    tags: [
      '100% Responsive',
      'TS',
      'Next.js',
      'Styled Components',
      'REST API',
      'Context API',
    ],
    link: 'https://books-nextjs-five.vercel.app/login',
    github: 'https://github.com/LucasMouraPereira/books-nextjs',
  },
  {
    name: 'Merry Christmas',
    shortDescription: 'Christmas card',
    description: '',
    tags: [
      '100% Responsive',
      'JS',
      'TS',
      'Next.js',
      'Styled Components',
      'react-type-animation',
    ],
    link: 'https://merrychristmas-beta.vercel.app/',
    github: 'https://github.com/LucasMouraPereira/marrychristmasy',
  },
  {
    name: 'Rick and Morty',
    shortDescription: 'Planets and their inhabitants from Rick and Morty',
    description: '',
    tags: [
      '100% Responsive',
      'TS',
      'Next.js',
      'Styled Components',
      'GraphQL',
      'Context API',
      'Swiper',
    ],
    link: 'https://rick-morty-neon-kappa.vercel.app/',
    github: 'https://github.com/LucasMouraPereira/Rick-Morty',
  },
  {
    name: 'This Portfolio',
    shortDescription: 'This portfolio of projects',
    description: '',
    tags: [
      '100% Responsive',
      'TS',
      'Next.js',
      'Styled Components',
      'REST API',
      'Context API',
      'Swiper',
      'Resend',
      'api router - Next.js',
    ],
    link: 'https://website-portfolio-five-gamma.vercel.app/',
    github: 'https://github.com/LucasMouraPereira/website-portfolio',
  },
  {
    name: 'Divine Providence System (SDP)',
    shortDescription: 'SDP donation system',
    description: '',
    tags: [
      '100% Responsive',
      'TS',
      'Next.js',
      'Styled Components',
      'CMS',
      'Next Auth',
      'REST API',
      'Context API',
    ],
    link: 'https://sdp-zeta.vercel.app/',
    github: 'https://github.com/LucasMouraPereira/sdp-frontend',
  },
]
