export const data = [
  {
    name: 'Books',
    shotDescription: 'Apresentação de catalogo de livros',
    description: '',
    tags: [
      '100% Responsivo',
      'TS',
      'NextJS',
      'Styled Components',
      'REST API',
      'ContextAPI',
    ],
    link: 'https://books-nextjs-five.vercel.app/login',
    github: 'https://github.com/LucasMouraPereira/books-nextjs',
  },
  {
    name: 'Merry Christmas',
    shotDescription: 'Cartão de Natal',
    description: '',
    tags: [
      '100% Responsivo',
      'JS',
      'TS',
      'NextJS',
      'Styled Components',
      'react-type-animation',
    ],
    link: 'https://merrychristmas-beta.vercel.app/',
    github: 'https://github.com/LucasMouraPereira/marrychristmasy',
  },
  {
    name: 'Rick and Morty',
    shotDescription: 'Planetas e seus habitantes de Rick and Morty',
    description: '',
    tags: [
      '100% Responsivo',
      'TS',
      'NextJS',
      'Styled Components',
      'GraphQL',
      'ContextAPI',
      'Swiper',
    ],
    link: 'https://rick-morty-neon-kappa.vercel.app/',
    github: 'https://github.com/LucasMouraPereira/Rick-Morty',
  },
  {
    name: 'Este portfolio',
    shotDescription: 'Este portifolio de projetos',
    description: '',
    tags: [
      '100% Responsivo',
      'TS',
      'NextJS',
      'Styled Components',
      'REST API',
      'ContextAPI',
      'Swiper',
      'Resend',
      'api router - NextJS',
    ],
    link: 'https://website-portfolio-five-gamma.vercel.app/',
    github: 'https://github.com/LucasMouraPereira/website-portfolio',
  },
  {
    name: 'Sistema Divina Providência(SDP)',
    shotDescription: 'Sistema de doações SDP',
    description: '',
    tags: [
      '100% Responsivo',
      'TS',
      'NextJS',
      'Styled Components',
      'CMS',
      'Next Auth',
      'REST API',
      'ContextAPI',
    ],
    link: 'https://sdp-zeta.vercel.app/',
    github: 'https://github.com/LucasMouraPereira/sdp-frontend',
  },
]
