export const data = [
  {
    name: 'LATAM PASS',
    jobTitle: 'Frontend Developer',
    company: 'Ioasys/Alpargatas',
    date: 'Feb 2024 - Present',
    text: 'Developed and maintained the LATAM Pass website using HTML, CSS, JavaScript, and frameworks like Bootstrap and jQuery.',
    link: 'https://latampass.latam.com/pt_br/',
  },
  {
    name: 'SDP - Divine Providence System',
    jobTitle: 'Frontend Developer',
    company: 'Vtecnologias',
    date: 'Jul 2023 - Dec 2023',
    text: 'Developed the SDP - Divine Providence System website using Next.js, Styled Components, TypeScript, and integrated with REST APIs.',
    link: 'https://sdp-frontend-seven.vercel.app/',
  },
  {
    name: 'Suvinil Institutional',
    jobTitle: 'Frontend Developer',
    company: 'Ioasys/Alpargatas',
    date: 'Oct 2020 - Dec 2023',
    text: 'Developed and maintained the Suvinil Institutional website using Next.js, Styled Components, TypeScript, and integrated with REST APIs.',
    link: 'https://www.suvinil.com.br/',
  },
  {
    name: 'Suvinil Store',
    jobTitle: 'Frontend Developer',
    company: 'Ioasys/Alpargatas',
    date: 'Oct 2020 - Dec 2023',
    text: 'Developed and maintained the Suvinil Store website using Next.js, Styled System, TypeScript, and integrated with REST APIs and Vtex.',
    link: 'https://loja.suvinil.com.br/',
  },
  {
    name: 'Glasu',
    jobTitle: 'Frontend Developer',
    company: 'Ioasys/Alpargatas',
    date: 'Oct 2020 - Dec 2023',
    text: 'Developed and maintained the Glasu website for Suvinil using Next.js, Styled System, TypeScript, and integrated with REST APIs.',
    link: 'https://www.glasu.com.br/',
  },
]
