export const data = [
  {
    name: 'Shopping Inter web',
    jobTitle: 'Frontend Developer',
    company: 'Act digital/Banco Inter',
    date: ' Agosto 2024 - atualmente',
    text: 'I am a developer on Shopping Inter, a digital marketplace connecting users to various retailers. Built with Next.js, TypeScript, Styled Components, and React Hook Form, it provides a seamless shopping experience with advanced search, personalized recommendations, and secure transactions. I contribute to feature development, performance optimization, and UI/UX improvements.',
    link: 'https://shopping.inter.co/',
  },
  {
    name: 'Ambev - Bees One Admin',
    jobTitle: 'Frontend Developer',
    company: 'Ioasys/Alpargatas',
    date: 'Abril 2024 - Agosto 2024',
    text: 'I was a developer on the BEES One Admin, a management platform for BEES. Built with Next.js, TypeScript, Styled Components, and React Hook Form (useFieldArray), it streamlines administrative tasks like user and order management. I worked on feature development, form handling, and UI/UX improvements.',
    link: 'https://one.bees.com/',
  },
  {
    name: 'Ambev - Bees One',
    jobTitle: 'Frontend Developer',
    company: 'Ioasys/Alpargatas',
    date: 'Abril 2024 - Agosto 2024',
    text: 'I was a developer on the BEES project, a digital ordering platform connecting retailers and wholesalers. Built with Next.js, TypeScript, and Styled Components, it enables users to browse catalogs, access real-time pricing, place orders 24/7, and manage invoices. I contributed to feature development, UI/UX improvements, and API integrations.',
    link: 'https://mybeesapp.com/',
  },
  {
    name: 'LATAM PASS',
    jobTitle: 'Frontend Developer',
    company: 'Ioasys/Alpargatas',
    date: 'Feb 2024 - Abril 2024',
    text: 'Developed and maintained the LATAM Pass website using HTML, CSS, JavaScript, and frameworks like Bootstrap and jQuery.',
    link: 'https://latampass.latam.com/pt_br/',
  },
  {
    name: 'SDP - Divine Providence System',
    jobTitle: 'Frontend Developer',
    company: 'Vtecnologias',
    date: 'Jul 2023 - Dec 2023',
    text: 'Developed the SDP - Divine Providence System website using Next.js, Styled Components, TypeScript, and integrated with REST APIs.',
    link: 'https://sdp-frontend-seven.vercel.app/',
  },
  {
    name: 'Suvinil Institutional',
    jobTitle: 'Frontend Developer',
    company: 'Ioasys/Alpargatas',
    date: 'Oct 2020 - Dec 2023',
    text: 'Developed and maintained the Suvinil Institutional website using Next.js, Styled Components, TypeScript, and integrated with REST APIs.',
    link: 'https://www.suvinil.com.br/',
  },
  {
    name: 'Suvinil Store',
    jobTitle: 'Frontend Developer',
    company: 'Ioasys/Alpargatas',
    date: 'Oct 2020 - Dec 2023',
    text: 'Developed and maintained the Suvinil Store website using Next.js, Styled System, TypeScript, and integrated with REST APIs and Vtex.',
    link: 'https://loja.suvinil.com.br/',
  },
  {
    name: 'Glasu',
    jobTitle: 'Frontend Developer',
    company: 'Ioasys/Alpargatas',
    date: 'Oct 2020 - Dec 2023',
    text: 'Developed and maintained the Glasu website for Suvinil using Next.js, Styled System, TypeScript, and integrated with REST APIs.',
    link: 'https://www.glasu.com.br/',
  },
]
